function [H]=SnapShot_Builder(varargin)
data=guidata(varargin{1});
 MChan=data{10}(1).Channel_Master;
 H.fh = figure('units','normalized',...
    'position',[.53 .5 .2 .25],...
    'menubar','none',...
    'name','Controller',...
    'numbertitle','off',...
    'resize','off','tag','Snapshot_Control');
H.TypeHeader = uicontrol('style','text',...
    'unit','normalized',...
    'position',[.3  .7-((-1)*.1) .9 .1],...
    'String','IM Type',...
    'fontsize',12,...
    'fontweight','bold',...
    'backgroundcolor',get(H.fh,'color'),...
    'HorizontalAlignment','left');
H.FillHeader = uicontrol('style','text',...
    'unit','normalized',...
    'position',[.68  .7-((-1)*.1) .9 .1],...
    'String','Fill',...
    'fontsize',12,...
    'fontweight','bold',...
    'backgroundcolor',get(H.fh,'color'),...
    'HorizontalAlignment','left');
NumChan=numel(data{9});
for i=1:NumChan
    if isempty(data{9}{i})
        E='off';
    else
        E='on';
    end
H.Channel(i)=uicontrol('style','text',...
    'unit','normalized',...
    'position',[.02  .7-((i-1)*.14) .9 .1],...
    'String',sprintf('%s:  ',data{10}(i).Channel_ID),...
    'fontsize',12,...
    'fontweight','bold',...
    'backgroundcolor',get(H.fh,'color'),...
    'HorizontalAlignment','left');
H.Fill(i)=uicontrol('style','popupmenu','units','normalized',...
    'position',[.6 .7-((i-1)*.14) .3 .11],'string',{'Mask','Perimeter'},'backgroundcolor',[1 1 1],...
    'fontsize',10,'parent',H.fh,'value',1,'enable',E);
H.Type(i) = uicontrol('Style','popupmenu','String',{'Binary','Intensity','None'},...
    'units','normalized','pos',[.25 .7-((i-1)*.14) .3 .11],'parent',H.fh,...
    'backgroundcolor',[1 1 1],'fontsize',10,'HorizontalAlignment','left','Value',1,'enable',E);
set(H.Type(i),'callback',{@EC,H.Type(i),H.Fill(i)})
end

mSix=Extract_Data(data,6,MChan,2);
H.ObjTitle=uicontrol('style','text','unit','normalized',...
    'position',[.02  .7-((NumChan+1-1)*.14) .9 .1],...
    'String','mROI #:',...
    'fontsize',12,...
    'fontweight','bold',...
    'backgroundcolor',get(H.fh,'color'),...
    'HorizontalAlignment','left');
H.ObjMenu=uicontrol('style','popupmenu','units','normalized',...
    'position',[.25 .7-((NumChan+1-1)*.14) .2 .11],'string',['All',arrayfun(@(x) num2str(x),1:size(mSix{1},1),'uniformoutput',0)],...
    'backgroundcolor',[1 1 1],...
    'fontsize',10,'parent',H.fh,'value',1);
H.SliceTitle=uicontrol('style','text','unit','normalized',...
    'position',[.48  .7-((NumChan+1-1)*.14) .9 .1],...
    'String','Slice',...
    'fontsize',12,...
    'fontweight','bold',...
    'backgroundcolor',get(H.fh,'color'),...
    'HorizontalAlignment','left');
H.SliceMenu=uicontrol('style','popupmenu','units','normalized',...
    'position',[.6 .7-((NumChan+1-1)*.14) .2 .11],'string',['Max Proj',arrayfun(@(x) num2str(x),1:data{1}.IMSize(3),'uniformoutput',0)],...
    'backgroundcolor',[1 1 1],...
    'fontsize',10,'parent',H.fh,'value',1);

H.Capture=uicontrol('style','pushbutton','units','normalized',...
    'position',[.4 .7-((NumChan+2-1)*.14) .2 .11],'string','Capture','backgroundcolor',...
    get(H.fh,'Color'),'fontsize',10,'callback',{@Stage_SnapShot,H,data},'visible','on','parent',H.fh);


end

function []=EC(varargin)
switch CallBack_Value_String(varargin{3})
    case 'Intensity'
        set(varargin{4},'string',{'All','Cut-Out'},'value',1,'enable','on')
    case 'Binary'
        set(varargin{4},'string',{'Mask','Perimeter'},'value',1,'enable','on')
    case 'None'
        set(varargin{4},'enable','off','string','None','value',1)

end
end
function []=Stage_SnapShot(varargin)

C.Image_Window=figure('tag','Comp_Window','visible','off');
C.Parent_Ax = axes('units','normalized','parent',C.Image_Window,...                                            
    'position',[0 0 1 1],...
    'fontsize',10,...
    'nextplot','replacechildren','XTickLabel',[],'YTickLabel',[],'XTick',[],'YTick',[],'visible','off');
Generate_SnapShot(1,1,varargin{3},varargin{4},C)

end