function H=AnaylsisPortalGUI(varargin)
[h,Modality,Type]=varargin{[1,3,4]};
data=guidata(h);
NumChan=sum(~cellfun(@isempty,data{9}));
MChan=data{10}(1).Channel_Master;
H=Contruct_GUIBase(data);

for i=1:3
   try 
       if sum(~cellfun(@isempty,data{9}{MChan}{2,9}(:,i+4)))==size(data{9}{MChan}{2,9},1)
           set(H.AnProp(2).AnaProp(i),'enable','on')
           set(H.AnProp(2).AnaProp(4:6),'enable','on')

       end
   catch
   end
end
Region_Objs=cell(size(data{9}{MChan}{2,9},1),1);
for i=1:size(data{9}{MChan}{2,9},1)
    Region_Objs{i,1}=mROI_Obj(data,i);
end

for i=1:NumChan
set(H.CProps.MenuAddParm(i),'visible','on')
set(H.CProps.TextAddParm(i),'visible','on')
set(H.GS.Cluster_Num(i),'visible','on')
set(H.GS.Cluster_Title(i),'visible','on')
set(H.GS.Cluster_Under(i),'visible','on')
set(H.GS.Cluster_Over(i),'visible','on')

end


switch Modality
    case 'Geo'
        for i=2:numel(H.CProps.TextAddParm)-1
            set(H.CProps.TextAddParm(i),'string',sprintf('Analysis %d',i-1))
            set(H.GS.Cluster_Title(i),'string',sprintf('Ana: %d',i-1))
            
            set(H.CProps.MenuAddParm(i),'callback',[])
        end
        set(H.CProps.Apply,'enable','on')
        set(H.fh,'Name','Between/Among')
        T=[{'Minimum'},{'Maximum'},{'Mean'}];
        Tags=[{'min'},{'max'},{'mean'}];
        
        for i=1:3
            set(H.GS.Within(i),'visible','on','string',T{i},'userdata',str2func(Tags{i}))
            set(H.GS.Among(i),'visible','on','string',T{i},'userdata',str2func(Tags{i}))
            
        end
        
        switch Type
            case 1
                set(H.AnaMethod(1),'visible','on','string','Min Distance: Perimeter')
                set(H.AnaMethod(2),'visible','on','string','Min Distance: Centroid')
                set(H.AnaMethod(3),'visible','on','string','Min Distance: Total')
                set(H.AnaMethod(4),'visible','on','string','Mean Distance: Perimeter')
                set(H.AnaMethod(5),'visible','on','string','Mean Distance: Centroid')
                set(H.AnaMethod(6),'visible','on','string','Max Distance: Perimeter')
                set(H.AnaMethod(7),'visible','on','string','Max Distance: Centroid')
                set(H.CProps.TextAddParm(1),'string','Referance')
                set(H.GS.Cluster_Title(1),'string','Ref:')
                set(H.CProps.MenuAddParm(1),'callback',[])
                set(H.CProps.Pairwise,'visible','on')
                
                      set(H.CProps.Apply,'callback',{@InterObj_Meassure,Region_Objs,H});
            case 2
                    set(H.AnaMethod(1),'visible','on','string','Number Voxels')
                set(H.AnaMethod(2),'visible','on','string','Voxel Volume')
                set(H.AnaMethod(3),'visible','on','string','Convex Hull Volume')
                set(H.AnaMethod(4),'visible','on','string','Surface Area')
                set(H.AnaMethod(5),'visible','on','string','Surface Area / Voxel Vol')
                set(H.AnaMethod(6),'visible','on','string','Surface Area / Convex Vol')

                set(H.AnaPropBG(2:4),'visible','off')

                set(H.CProps.Apply,'callback',{@Geometric_Meassure,Region_Objs,H});

         
            case 4
                
                set(H.AnaMethod(1),'visible','on','string','Eroding Shells')
                set(H.AnaMethod(2),'visible','on','string','Expanding Shells')
                H.AnaMethod(3)  = uicontrol('Style','text','String','# Shells',...
                    'units','normalized','pos',[.05 .8571-((3-1)*.1429) .9 .1],'parent',H.AnaylsisMethods,...
                    'backgroundcolor',get(H.fh,'color'),'fontsize',10,'visible','on');
            H.AnaMethod(4)  = uicontrol('Style','edit','String','3',...
                    'units','normalized','pos',[.3 .8571-((4-1)*.1429) .45 .1],'parent',H.AnaylsisMethods,...
                    'fontsize',10,'visible','on');
                set(H.CProps.TextAddParm(1),'string','Shell Chan')
                
                set(H.fh,'Name','Shells')
                set(H.AnProp(2).AnaProp(1:5),'visible','off')
                set(H.CProps.Apply,'callback',{@Shell_Meassure,Region_Objs,H,Type});
                set(H.AnaPropBG(2),'visible','on')

                
        end
    case 'Int'
        keyboard
end
end
function BaseGUI=Contruct_GUIBase(data)
NumChan=numel(data{9});
MChan=data{10}(1).Channel_Master;

BaseGUI.fh = figure('units','normalized',...
'position',[.1 .15 .3 .65],...
'menubar','none',...
'name','Analyzer',...
'numbertitle','off',...
'resize','off','visible','on');
%% Channel Properties
BaseGUI.ChannelProps=uibuttongroup('unit','normalized',...
'position',[.025 .6 .45 .4],...
'title','Channel Properties',...
'fontsize',12,...
'fontweight','bold',...
'backgroundcolor',get(BaseGUI.fh,'color'),'parent',BaseGUI.fh,'visible','on','HandleVisibility','on');
z=1;

Channels=cell(NumChan,1);
for i=1:NumChan
    if ~isempty(data{9}{i})
        Channels{i,1}=data{10}(i).Channel_ID;
    else
     Channels{i,1}='#########$#$$#' ;  
    end
end
Channels=['None';Channels(~strcmp('#########$#$$#',Channels))];
for i=1:NumChan
    if ~isempty(data{9}{i})
        BaseGUI.CProps.MenuAddParm(z) = uicontrol('Style','popupmenu','String',Channels,...
            'units','normalized','pos',[.35 .8-((z-1)*.15) .5 .1],'parent',BaseGUI.ChannelProps,'enable','on','visible','off');
        BaseGUI.CProps.TextAddParm(z) = uicontrol('Style','text','String',sprintf('Analysis %d',i),...
            'units','normalized','pos',[.001 .8-((z-1)*.15) .32 .1],'parent',BaseGUI.ChannelProps,...
            'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',12,'visible','off');
    z=z+1;    
    end
end

set(BaseGUI.CProps.MenuAddParm(1),'string',Channels(2:end))
BaseGUI.CProps.MenuAddParm(z)=uicontrol('Style','popupmenu','String',['All',arrayfun(@(x) num2str(x),1:size(data{9}{MChan}{2,9},1),'uniformoutput',0)],...
    'units','normalized','pos',[.35 .2 .5 .1],'parent',BaseGUI.ChannelProps);
BaseGUI.CProps.TextAddParm(z) = uicontrol('Style','text','String','Index',...
    'units','normalized','pos',[.001 .2 .32 .1],'parent',BaseGUI.ChannelProps,...
    'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',12,'tag','Index:');
BaseGUI.CProps.Pairwise  = uicontrol('Style','checkbox','String','All Pairwise',...
'units','normalized','pos',[.35 .1 .65 .1],'parent',BaseGUI.ChannelProps,...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','off');
BaseGUI.CProps.Apply  = uicontrol('Style','pushbutton','String','Calculate',...
'units','normalized','pos',[.35 0 .3 .1],'parent',BaseGUI.ChannelProps,...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',12,'callback',@Analyze,'Enable','off');

for i=1:z
    set(BaseGUI.CProps.MenuAddParm(i),'userdata',BaseGUI.CProps.MenuAddParm,'callback',{@EnableApply,BaseGUI.CProps.Apply})
end
%% Anaylsis Methods

BaseGUI.AnaylsisMethods=uibuttongroup('unit','normalized',...
'position',[.025 .02 .45 .425],...
'title','Anaylsis Methods',...
'fontsize',12,...
'fontweight','bold',...
'backgroundcolor',get(BaseGUI.fh,'color'),'parent',BaseGUI.fh,'visible','on','HandleVisibility','on');
for i=1:10
BaseGUI.AnaMethod(i)  = uicontrol('Style','checkbox','String',sprintf('Methods %d',i),...
'units','normalized','pos',[.05 .8571-((i-1)*.1) .9 .1],'parent',BaseGUI.AnaylsisMethods,...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','off');
end

%% Force Signal Groups
BaseGUI.SignalsGroups=uibuttongroup('unit','normalized',...
    'position',[.025 .45 .45 .15],...
    'title','Signals Grouping',...
    'fontsize',12,...
    'fontweight','bold',...
    'backgroundcolor',get(BaseGUI.fh,'color'),'parent',BaseGUI.fh,'visible','on','HandleVisibility','on');

for i=1:4
BaseGUI.GS.Cluster_Title(i)  = uicontrol('Style','text','String',sprintf('Ana: %d',i),...
    'units','normalized','pos',[.05 .9-(.225*(i)) .15 .225],'parent',BaseGUI.SignalsGroups,...
    'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','off');
BaseGUI.GS.Cluster_Num(i)  = uicontrol('Style','edit','String',nan,...
    'units','normalized','pos',[.3 .9-(.225*(i)) .15 .225],'parent',BaseGUI.SignalsGroups,...
    'backgroundcolor',[1 1 1],'fontsize',10,'visible','off');
BaseGUI.GS.Cluster_Under(i)  = uicontrol('Style','checkbox','String','Up',...
    'units','normalized','pos',[.45 .9-(.225*(i)) .25 .225],'parent',BaseGUI.SignalsGroups,...
    'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','off','value',1);
BaseGUI.GS.Cluster_Over(i)  = uicontrol('Style','checkbox','String','Down',...
    'units','normalized','pos',[.7 .9-(.225*(i)) .3 .225],'parent',BaseGUI.SignalsGroups,...
    'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','off','value',1);

end
%% Anaylsis Properties
BaseGUI.AnaylsisProps=uibuttongroup('unit','normalized',...
'position',[.525 .55 .45 .45],...
'title','Analysis Prop',...
'fontsize',12,...
'fontweight','bold',...
'backgroundcolor',get(BaseGUI.fh,'color'),'parent',BaseGUI.fh,'visible','on','HandleVisibility','on');

% Dimensionality Of anaylsis
BaseGUI.AnaPropBG(1)=uibuttongroup('unit','normalized',...
'position',[.025 .85 .95 .15],...
'title','Dimension',...
'fontsize',10,...
'fontweight','bold',...
'backgroundcolor',get(BaseGUI.fh,'color'),'parent',BaseGUI.AnaylsisProps,'visible','on','HandleVisibility','on','tag','Dimension');
BaseGUI.AnProp(1).AnaProp(1)  = uicontrol('Style','radio','String','2D',...
'units','normalized','pos',[.05 .20 .45 .9],'parent',BaseGUI.AnaPropBG(1),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'tag','Dim: 2D');
BaseGUI.AnProp(1).AnaProp(2)  = uicontrol('Style','radio','String','3D',...
'units','normalized','pos',[.5 .20 .45 .9],'parent',BaseGUI.AnaPropBG(1),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'tag','Dim: 3D','value',1);



% Centroid or Edge/Perimeter Measurements
BaseGUI.AnaPropBG(3)=uibuttongroup('unit','normalized',...
'position',[.025 .7 .95 .15],...
'title','Measure Position',...
'fontsize',10,...
'fontweight','bold',...
'backgroundcolor',get(BaseGUI.fh,'color'),'parent',BaseGUI.AnaylsisProps,'visible','on','HandleVisibility','on','tag','Measure Position');
BaseGUI.AnProp(3).AnaProp(1)  = uicontrol('Style','checkbox','String','Centroid',...
'units','normalized','pos',[.05 .2 .45 .9],'parent',BaseGUI.AnaPropBG(3),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10);
BaseGUI.AnProp(3).AnaProp(2)  = uicontrol('Style','checkbox','String','Total',...
'units','normalized','pos',[.5 .2 .45 .9],'parent',BaseGUI.AnaPropBG(3),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10);


%Normlization Metric
BaseGUI.AnaPropBG(2)=uibuttongroup('unit','normalized',...
'position',[.025 .3 .95 .4],...
'title','Simulated Points',...
'fontsize',10,...
'fontweight','bold',...
'backgroundcolor',get(BaseGUI.fh,'color'),'parent',BaseGUI.AnaylsisProps,'visible','on','HandleVisibility','on','tag','Simulation Basis');
BaseGUI.AnProp(2).AnaProp(1)  = uicontrol('Style','checkbox','String','Nearest Neighboor',...
'units','normalized','pos',[.05 .84 .55 .15],'parent',BaseGUI.AnaPropBG(2),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'enable','off');
BaseGUI.AnProp(2).AnaProp(2)  = uicontrol('Style','checkbox','String','Wiggle',...
'units','normalized','pos',[.6 .84 .4 .15],'parent',BaseGUI.AnaPropBG(2),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'enable','off');
BaseGUI.AnProp(2).AnaProp(3)  = uicontrol('Style','checkbox','String','Inside Convex Hull',...
'units','normalized','pos',[.22 .6175 .66 .15],'parent',BaseGUI.AnaPropBG(2),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'enable','off','HorizontalAlignment','center');
BaseGUI.AnProp(2).AnaProp(4)  = uicontrol('Style','radio','String','Free Ends',...
'units','normalized','pos',[.05 .365 .45 .15],'parent',BaseGUI.AnaPropBG(2),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'enable','off');
BaseGUI.AnProp(2).AnaProp(5)  = uicontrol('Style','radio','String','Anchor End',...
'units','normalized','pos',[.5 .365 .45 .15],'parent',BaseGUI.AnaPropBG(2),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'value',1,'enable','off');
BaseGUI.AnProp(2).AnaProp(6)  = uicontrol('Style','checkbox','String','Estimate Simulation Error',...
'units','normalized','pos',[.1 .1125 .9 .15],'parent',BaseGUI.AnaPropBG(2),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'enable','off','callback',{@Error_Estimation});

BaseGUI.AnaPropBG(4)=uibuttongroup('unit','normalized',...
'position',[.025 .05 .95 .25],...
'title','Simulated Points: Error Estimation',...
'fontsize',10,...
'fontweight','bold','visible','off',...
'backgroundcolor',get(BaseGUI.fh,'color'),'parent',BaseGUI.AnaylsisProps,'HandleVisibility','on','tag','Simulation Basis');

BaseGUI.AnProp(4).AnaProp(1)  = uicontrol('Style','text','String','Bootstrap #',...
'units','normalized','pos',[.05 .7 .35 .3],'parent',BaseGUI.AnaPropBG(4),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','on');
BaseGUI.AnProp(4).AnaProp(2)  = uicontrol('Style','edit','String',10000,...
'units','normalized','pos',[.05 .3 .3 .3],'parent',BaseGUI.AnaPropBG(4),...
'backgroundcolor',[1 1 1],'fontsize',10,'visible','on');

BaseGUI.AnProp(4).AnaProp(3)  = uicontrol('Style','text','String','Confidence Interval',...
'units','normalized','pos',[.5 .6 .45 .4],'parent',BaseGUI.AnaPropBG(4),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','on');
BaseGUI.AnProp(4).AnaProp(4)  = uicontrol('Style','edit','String',.95,...
'units','normalized','pos',[.58 .3 .3 .3],'parent',BaseGUI.AnaPropBG(4),...
'backgroundcolor',[1 1 1],'fontsize',10,'visible','on');

set(BaseGUI.AnProp(2).AnaProp(6),'callback',{@Error_Estimation,BaseGUI})



%% Group Anaylsis
BaseGUI.GroupProps=uibuttongroup('unit','normalized',...
'position',[.525 .15 .45 .4],...
'title','Group Anaylsis',...
'fontsize',12,...
'fontweight','bold',...
'backgroundcolor',get(BaseGUI.fh,'color'),'parent',BaseGUI.fh,'visible','on','HandleVisibility','on');


BaseGUI.GProps(1)=uibuttongroup('unit','normalized',...
'position',[.025 .5 .95 .475],...
'title','Within Channel Summary',...
'fontsize',10,...
'fontweight','bold',...
'backgroundcolor',get(BaseGUI.fh,'color'),'parent',BaseGUI.GroupProps,'visible','on','HandleVisibility','on');

for i=1:3
BaseGUI.GS.Within(i) = uicontrol('Style','checkbox','String','Summary',...
'units','normalized','pos',[.025 .8-((i-1)*.2) .475 .15],'parent',BaseGUI.GProps(1),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','off');
BaseGUI.GS.Within(3+i) = uicontrol('Style','checkbox','String','Summary',...
'units','normalized','pos',[.5 .8-((i-1)*.2) .475 .15],'parent',BaseGUI.GProps(1),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','off');
end
BaseGUI.GS.Within_Global = uicontrol('Style','checkbox','String','Use Global',...
'units','normalized','pos',[.25 .01 .5 .15],'parent',BaseGUI.GProps(1),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','on');

BaseGUI.GProps(2)=uibuttongroup('unit','normalized',...
'position',[.025 .025 .95 .475],...
'title','Among Channel Summary',...
'fontsize',10,...
'fontweight','bold',...
'backgroundcolor',get(BaseGUI.fh,'color'),'parent',BaseGUI.GroupProps,'visible','on','HandleVisibility','on');
BaseGUI.GS.Among_Title  = uicontrol('Style','text','String','Number of Clusters:',...
'units','normalized','pos',[.025 .8 .5 .2],'parent',BaseGUI.GProps(2),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','on');
BaseGUI.GS.Among_Num  = uicontrol('Style','edit','String',nan,...
'units','normalized','pos',[.525 .8 .28 .2],'parent',BaseGUI.GProps(2),...
'backgroundcolor',[1 1 1],'fontsize',10,'visible','on');

for i=2:4
BaseGUI.GS.Among(i-1) = uicontrol('Style','checkbox','String','Summary',...
'units','normalized','pos',[.025 .8-((i-1)*.2) .475 .15],'parent',BaseGUI.GProps(2),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','off');
BaseGUI.GS.Among(2+i) = uicontrol('Style','checkbox','String','Summary',...
'units','normalized','pos',[.5 .8-((i-1)*.2) .475 .15],'parent',BaseGUI.GProps(2),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','off');
end

%{
BaseGUI.GrpProps(1) = uicontrol('Style','checkbox','String','Perform Group Anaylsis',...
'units','normalized','pos',[.05 .80 .9 .15],'parent',BaseGUI.GroupProps,...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'HorizontalAlignment','left','value',0,'tag','Change Master','value',0,'callback',@UnlockGroup);


%}
BaseGUI.InputName=uicontrol('style','text',...
    'unit','normalized',...
    'position',[.50 .015 .45 .05],...
    'String',sprintf('%s %s',data{10}(1).Image_ID,data{10}(1).Image_Number),...
    'fontsize',12,...
    'backgroundcolor',get(BaseGUI.fh,'color'),...
    'HorizontalAlignment','left');
BaseGUI.SavePathString=uicontrol('style','text',...
    'unit','normalized',...
    'position',[.70 0 .2 .11],...
    'String',pwd,...
    'fontsize',8,...
    'backgroundcolor',get(BaseGUI.fh,'color'),...
    'HorizontalAlignment','left');
BaseGUI.SavePath=uicontrol('style','pushbutton',...
    'unit','normalized',...
    'position',[.50 .075 .2 .05],...
    'String','Save Path',...
    'fontsize',12,...
    'backgroundcolor',get(BaseGUI.fh,'color'),...
    'HorizontalAlignment','left','callback',{@setSavePath,BaseGUI});

set(BaseGUI.CProps.Pairwise,'callback',{@Pairwise,BaseGUI})
end
function []=EnableApply(varargin)
H=get(varargin{1},'userdata');
Current_Setting=cell(numel(H),1);
for i=1:numel(H)
    Current_Setting{i,1}=CallBack_Value_String(H(i));
end
Current_Setting=Current_Setting(~strcmp(Current_Setting,'None'));
if numel(unique(Current_Setting))==numel(Current_Setting)
    set(varargin{3},'enable','on')
else
    set(varargin{3},'enable','off')
end

end
function []=Error_Estimation(varargin)
if get(varargin{1},'value')==1
    set(varargin{3}.AnaPropBG(4),'visible','on')
else
   set(varargin{3}.AnaPropBG(4),'visible','off') 
end
end
function []=setSavePath(varargin)
Path=uigetdir;
set(varargin{3}.SavePathString,'string',Path);
end

function []=Pairwise(varargin)
H=varargin{3};

switch get(varargin{1},'value')
    case 0
Set='on';        
S=get(H.CProps.MenuAddParm(2),'string');
        set(H.CProps.MenuAddParm(1),'enable',Set,'value',1,'string',S(2:end))
    case 1
Set='off';
        set(H.CProps.MenuAddParm(1),'enable',Set,'value',1,'string','None')

end
        set(H.GS.Cluster_Num(1),'enable',Set)
        set(H.GS.Cluster_Title(1),'enable',Set)
        set(H.CProps.TextAddParm(1),'enable',Set)
end
