function H=AnaylsisPortalGUI(varargin)
[h,Modality,Type]=varargin{[1,3,4]};
data=guidata(h);
NumChan=numel(data{9});
MChan=data{10}(1).Channel_Master;
H=Contruct_GUIBase(data);

for i=1:3
   try 
       if sum(~cellfun(@isempty,data{9}{MChan}{2,9}(:,i+4)))==size(data{9}{MChan}{2,9},1)
           set(H.AnProp(2).AnaProp(i),'enable','on')
           set(H.AnProp(2).AnaProp(4:7),'visible','on')

       end
   catch
   end
end
Region_Objs=cell(size(data{9}{MChan}{2,9},1),1);
for i=1:size(data{9}{MChan}{2,9},1)
    Region_Objs{i,1}=mROI_Obj(data,i);
end

switch Modality
    case 'Geo'
        switch Type
            case 1
                set(H.AnaMethod(1),'visible','on','string','Volume: Voxel')
                set(H.AnaMethod(2),'visible','on','string','Volume: Convex Hull')
                set(H.AnaMethod(3),'visible','on','string','Longest Line: Through Centroid')
                set(H.AnaMethod(4),'visible','on','string','Shortest Line: Through Centroid')
                set(H.AnaMethod(5),'visible','on','string','Surface Area: Voxel')
                set(H.AnaMethod(6),'visible','on','string','Surface Area: Convex Hull')
            case {2,3}
                set(H.AnaMethod(1),'visible','on','string','Min Distance: Perimeter')
                set(H.AnaMethod(2),'visible','on','string','Min Distance: Centroid')
                set(H.AnaMethod(3),'visible','on','string','Mean Distance: Perimeter')
                set(H.AnaMethod(4),'visible','on','string','Mean Distance: Centroid')
                set(H.AnaMethod(5),'visible','on','string','Max Distance: Perimeter')
                set(H.AnaMethod(6),'visible','on','string','Max Distance: Centroid')
                %set(H.AnaMethod(7),'visible','on','string','Radial Distance')
                set(H.CProps.TextAddParm(1),'string','Referance')
                set(H.CProps.MenuAddParm(1),'callback',[])
                for i=2:numel(H.CProps.TextAddParm)
                    set(H.CProps.TextAddParm(i),'string',sprintf('Analysis %d',i-1))
                    set(H.CProps.MenuAddParm(i),'callback',[])
                end
                set(H.CProps.Apply,'enable','on')  
                if Type==2
                    set(H.fh,'Name','Anchored End')
                else
                    set(H.fh,'Name','Free Ends')
                end
                
                set(H.CProps.Apply,'callback',{@InterObj_Meassure,Region_Objs,H,Type});
            case 4
                
                set(H.AnaMethod(1),'visible','on','string','Eroding Shells')
                set(H.AnaMethod(2),'visible','on','string','Expanding Shells')
                H.AnaMethod(3)  = uicontrol('Style','text','String','# Shells',...
                    'units','normalized','pos',[.05 .8571-((3-1)*.1429) .9 .1],'parent',H.AnaylsisMethods,...
                    'backgroundcolor',get(H.fh,'color'),'fontsize',10,'visible','on');
            H.AnaMethod(4)  = uicontrol('Style','edit','String','3',...
                    'units','normalized','pos',[.3 .8571-((4-1)*.1429) .45 .1],'parent',H.AnaylsisMethods,...
                    'fontsize',10,'visible','on');
                set(H.CProps.TextAddParm(1),'string','Shell Chan')
                for i=2:numel(H.CProps.TextAddParm)
                    set(H.CProps.TextAddParm(i),'string',sprintf('Analysis %d',i-1))
                end
                set(H.fh,'Name','Shells')
                set(H.CProps.Apply,'callback',{@Shell_Meassure,Region_Objs,H,Type});
                set(H.AnaPropBG(2),'visible','on')

                
        end
    case 'Int'
        keyboard
end
end
function BaseGUI=Contruct_GUIBase(data)
NumChan=numel(data{9});
MChan=data{10}(1).Channel_Master;

BaseGUI.fh = figure('units','normalized',...
'position',[.1 .35 .3 .5],...
'menubar','none',...
'name','Analyzer',...
'numbertitle','off',...
'resize','off','visible','on');
%% Channel Properties
BaseGUI.ChannelProps=uibuttongroup('unit','normalized',...
'position',[.025 .40 .45 .6],...
'title','Channel Properties',...
'fontsize',12,...
'fontweight','bold',...
'backgroundcolor',get(BaseGUI.fh,'color'),'parent',BaseGUI.fh,'visible','on','HandleVisibility','on');
z=1;

Channels=cell(NumChan,1);
for i=1:NumChan
    if ~isempty(data{9}{i})
        Channels{i,1}=data{10}(i).Channel_ID;
    else
     Channels{i,1}='#########$#$$#' ;  
    end
end
Channels=['None';Channels(~strcmp('#########$#$$#',Channels))];
for i=1:NumChan
    if ~isempty(data{9}{i})
        BaseGUI.CProps.MenuAddParm(z) = uicontrol('Style','popupmenu','String',Channels,...
            'units','normalized','pos',[.35 .8-((z-1)*.15) .5 .1],'parent',BaseGUI.ChannelProps,'enable','on');
        BaseGUI.CProps.TextAddParm(z) = uicontrol('Style','text','String',sprintf('Analysis %d',i),...
            'units','normalized','pos',[.001 .8-((z-1)*.15) .32 .1],'parent',BaseGUI.ChannelProps,...
            'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',12);
    z=z+1;    
    end
end
set(BaseGUI.CProps.MenuAddParm(1),'string',Channels(2:end))
BaseGUI.CProps.MenuAddParm(z)=uicontrol('Style','popupmenu','String',['All',arrayfun(@(x) num2str(x),1:size(data{9}{MChan}{2,9},1),'uniformoutput',0)],...
    'units','normalized','pos',[.35 .2 .5 .1],'parent',BaseGUI.ChannelProps);
BaseGUI.CProps.TextAddParm(z) = uicontrol('Style','text','String','Index',...
    'units','normalized','pos',[.001 .2 .32 .1],'parent',BaseGUI.ChannelProps,...
    'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',12,'tag','Index:');
BaseGUI.CProps.Apply  = uicontrol('Style','pushbutton','String','Calculate',...
'units','normalized','pos',[.35 0 .3 .1],'parent',BaseGUI.ChannelProps,...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',12,'callback',@Analyze,'Enable','off');

for i=1:z
    set(BaseGUI.CProps.MenuAddParm(i),'userdata',BaseGUI.CProps.MenuAddParm,'callback',{@EnableApply,BaseGUI.CProps.Apply})
end

%% Anaylsis Properties
BaseGUI.AnaylsisProps=uibuttongroup('unit','normalized',...
'position',[.525 .40 .45 .6],...
'title','Analysis Prop',...
'fontsize',12,...
'fontweight','bold',...
'backgroundcolor',get(BaseGUI.fh,'color'),'parent',BaseGUI.fh,'visible','on','HandleVisibility','on');
% Dimensionality Of anaylsis
BaseGUI.AnaPropBG(1)=uibuttongroup('unit','normalized',...
'position',[.025 .82 .95 .18],...
'title','Dimension',...
'fontsize',12,...
'fontweight','bold',...
'backgroundcolor',get(BaseGUI.fh,'color'),'parent',BaseGUI.AnaylsisProps,'visible','on','HandleVisibility','on','tag','Dimension');
BaseGUI.AnProp(1).AnaProp(1)  = uicontrol('Style','radio','String','2D',...
'units','normalized','pos',[.05 .20 .45 .9],'parent',BaseGUI.AnaPropBG(1),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',11,'tag','Dim: 2D');
BaseGUI.AnProp(1).AnaProp(2)  = uicontrol('Style','radio','String','3D',...
'units','normalized','pos',[.5 .20 .45 .9],'parent',BaseGUI.AnaPropBG(1),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',11,'tag','Dim: 3D','value',1);

%Normlization Metric
BaseGUI.AnaPropBG(2)=uibuttongroup('unit','normalized',...
'position',[.025 .47 .95 .35],...
'title','Normlization Metric',...
'fontsize',12,...
'fontweight','bold',...
'backgroundcolor',get(BaseGUI.fh,'color'),'parent',BaseGUI.AnaylsisProps,'visible','on','HandleVisibility','on','tag','Simulation Basis');
BaseGUI.AnProp(2).AnaProp(1)  = uicontrol('Style','checkbox','String','Nearest Neighboor',...
'units','normalized','pos',[.05 .75 .9 .2],'parent',BaseGUI.AnaPropBG(2),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'enable','off');
BaseGUI.AnProp(2).AnaProp(2)  = uicontrol('Style','checkbox','String','Linear Interpolation',...
'units','normalized','pos',[.05 .45 .9 .2],'parent',BaseGUI.AnaPropBG(2),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'enable','off');
BaseGUI.AnProp(2).AnaProp(3)  = uicontrol('Style','checkbox','String','Inside Convex Hull',...
'units','normalized','pos',[.05 .15 .9 .2],'parent',BaseGUI.AnaPropBG(2),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'enable','off');

BaseGUI.AnProp(2).AnaProp(4)  = uicontrol('Style','text','String','Bootstrap #',...
'units','normalized','pos',[.6 .85 .35 .2],'parent',BaseGUI.AnaPropBG(2),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','off');
BaseGUI.AnProp(2).AnaProp(5)  = uicontrol('Style','edit','String',10000,...
'units','normalized','pos',[.63 .65 .3 .2],'parent',BaseGUI.AnaPropBG(2),...
'backgroundcolor',[1 1 1],'fontsize',10,'visible','off');

BaseGUI.AnProp(2).AnaProp(6)  = uicontrol('Style','text','String','Confidence Interval',...
'units','normalized','pos',[.6 .25 .35 .4],'parent',BaseGUI.AnaPropBG(2),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','off');
BaseGUI.AnProp(2).AnaProp(7)  = uicontrol('Style','edit','String',.95,...
'units','normalized','pos',[.63 .04 .3 .2],'parent',BaseGUI.AnaPropBG(2),...
'backgroundcolor',[1 1 1],'fontsize',10,'visible','off');


% Centroid or Edge/Perimeter Measurements
BaseGUI.AnaPropBG(3)=uibuttongroup('unit','normalized',...
'position',[.025 .28 .95 .18],...
'title','Measure Position',...
'fontsize',12,...
'fontweight','bold',...
'backgroundcolor',get(BaseGUI.fh,'color'),'parent',BaseGUI.AnaylsisProps,'visible','on','HandleVisibility','on','tag','Measure Position');
BaseGUI.AnProp(3).AnaProp(1)  = uicontrol('Style','checkbox','String','Centroid',...
'units','normalized','pos',[.05 .2 .45 .9],'parent',BaseGUI.AnaPropBG(3),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10);
BaseGUI.AnProp(3).AnaProp(2)  = uicontrol('Style','checkbox','String','Total',...
'units','normalized','pos',[.5 .2 .45 .9],'parent',BaseGUI.AnaPropBG(3),...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10);

%% Anaylsis Methods

BaseGUI.AnaylsisMethods=uibuttongroup('unit','normalized',...
'position',[.025 .025 .45 .35],...
'title','Anaylsis Methods',...
'fontsize',12,...
'fontweight','bold',...
'backgroundcolor',get(BaseGUI.fh,'color'),'parent',BaseGUI.fh,'visible','on','HandleVisibility','on');
for i=1:8
BaseGUI.AnaMethod(i)  = uicontrol('Style','checkbox','String',sprintf('Methods %d',i),...
'units','normalized','pos',[.05 .8571-((i-1)*.1429) .9 .1],'parent',BaseGUI.AnaylsisMethods,...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','off');
end

%% Group Anaylsis
BaseGUI.GroupProps=uibuttongroup('unit','normalized',...
'position',[.525 .15 .45 .225],...
'title','Group Anaylsis',...
'fontsize',12,...
'fontweight','bold',...
'backgroundcolor',get(BaseGUI.fh,'color'),'parent',BaseGUI.fh,'visible','on','HandleVisibility','on');

BaseGUI.GrpProps(1) = uicontrol('Style','checkbox','String','Perform Group Anaylsis',...
'units','normalized','pos',[.05 .80 .9 .15],'parent',BaseGUI.GroupProps,...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'HorizontalAlignment','left','value',0,'tag','Change Master','value',0,'callback',@UnlockGroup);


BaseGUI.GrpProps(2) = uicontrol('Style','checkbox','String','Within Group',...
'units','normalized','pos',[.1 .60 .9 .15],'parent',BaseGUI.GroupProps,...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','off');
%{
BaseGUI.GrpProps(3) = uicontrol('Style','checkbox','String','Report Indvl',...
'units','normalized','pos',[.1 .40 .9 .15],'parent',BaseGUI.GroupProps,...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','off');
BaseGUI.GrpProps(4) = uicontrol('Style','checkbox','String','Report Metrics',...
'units','normalized','pos',[.1 .20 .9 .15],'parent',BaseGUI.GroupProps,...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','off');
%}
BaseGUI.GrpProps(5)  = uicontrol('Style','text','String','Group #',...
'units','normalized','pos',[.5 .5 .4 .2],'parent',BaseGUI.GroupProps,...
'backgroundcolor',get(BaseGUI.fh,'color'),'fontsize',10,'visible','off');
BaseGUI.GrpProps(6)  = uicontrol('Style','edit','String',2,...
'units','normalized','pos',[.6 .3 .2 .2],'parent',BaseGUI.GroupProps,...
'backgroundcolor',[1 1 1],'fontsize',10,'visible','off');
set(BaseGUI.GrpProps(1),'Userdata',BaseGUI.GrpProps)


BaseGUI.InputName=uicontrol('style','text',...
    'unit','normalized',...
    'position',[.50 .015 .45 .05],...
    'String',sprintf('%s %s',data{10}(1).Image_ID,data{10}(1).Image_Number),...
    'fontsize',12,...
    'backgroundcolor',get(BaseGUI.fh,'color'),...
    'HorizontalAlignment','left');
BaseGUI.SavePathString=uicontrol('style','text',...
    'unit','normalized',...
    'position',[.70 0 .2 .11],...
    'String',pwd,...
    'fontsize',8,...
    'backgroundcolor',get(BaseGUI.fh,'color'),...
    'HorizontalAlignment','left');
BaseGUI.SavePath=uicontrol('style','pushbutton',...
    'unit','normalized',...
    'position',[.50 .075 .2 .05],...
    'String','Save Path',...
    'fontsize',12,...
    'backgroundcolor',get(BaseGUI.fh,'color'),...
    'HorizontalAlignment','left','callback',{@setSavePath,BaseGUI});


end
function []=EnableApply(varargin)
H=get(varargin{1},'userdata');
Current_Setting=cell(numel(H),1);
for i=1:numel(H)
    Current_Setting{i,1}=CallBack_Value_String(H(i));
end
Current_Setting=Current_Setting(~strcmp(Current_Setting,'None'));
if numel(unique(Current_Setting))==numel(Current_Setting)
    set(varargin{3},'enable','on')
else
    set(varargin{3},'enable','off')
end

end
function []=UnlockGroup(varargin)
H=get(varargin{1},'userdata');
switch get(varargin{1},'value')
    case 1
        toggle='on';
    case 0
        toggle='off';
        
end
for i=2:numel(H)
    set(H(i),'visible',toggle)
end
end
function []=setSavePath(varargin)
Path=uigetdir;
set(varargin{3}.SavePathString,'string',Path);
end
