function [Composite_Sequence, Color_Chan,SequenceDirectory]=ImportImageSequence(varargin)
%IMPORTFILE(FirstFiletoRead)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 27-Jul-2012 11:44:25

% Import the file
if isempty(varargin)
    
SequenceDirectory=uigetdir('Choose Directory with Sequence Files');
else
    SequenceDirectory=varargin{1};
end
fNames=dir(SequenceDirectory);
addpath(SequenceDirectory)

Z_Val=zeros(numel(fNames),1);
C_Val=zeros(numel(fNames),1);
Z_str=cell(numel(fNames),1);
C_str=cell(numel(fNames),1);
Tiff=false(numel(fNames),1);
for i=1:numel(fNames)
    if isempty(regexp(fNames(i).name,'.tif', 'once'))
    Tiff(i,1)=false;    
    else
    Tiff(i,1)=true;    
    end
end
fNames=fNames(Tiff);
for i=1:numel(fNames)
underScorePos=regexp(fNames(i).name,'_');
endName_Index=regexp(fNames(i).name,'\.');
tZ_Index=regexp(fNames(i).name,'z');
tZ_Index=tZ_Index(end);
tChannel_Index=regexp(fNames(i).name,'c');
tChannel_Index=tChannel_Index(end);

if tZ_Index<tChannel_Index
Z_Index=tZ_Index+((regexp(fNames(i).name(tZ_Index:tChannel_Index),'\d'))-1);
Channel_Index=tChannel_Index+((regexp(fNames(i).name(tChannel_Index:endName_Index),'\d'))-1);

else
Z_Index=tZ_Index+((regexp(fNames(i).name(tZ_Index:endName_Index),'\d'))-1);
Channel_Index=tChannel_Index+((regexp(fNames(i).name(tChannel_Index:tChannel_Index),'\d'))-1);
end


Z_str{i,:}=fNames(i).name(Z_Index);
C_str{i,:}=fNames(i).name(Channel_Index);

Z_Val(i,:)=str2double(Z_str{i,:});
C_Val(i,1)=str2double(C_str{i,:});
end

Z_Val(C_Val==0)=[];
C_Val(C_Val==0)=[];
[~,sortI]=sort(Z_Val,'ascend');
Z_Val=Z_Val(sortI);
C_Val=C_Val(sortI);

num_Chan=max(C_Val);

file_name=fNames(3).name;

temp=importdata(file_name);
if isstruct(temp)
    temp=temp.cdata;
else
end
[A,B]=size(temp);
ctype=class(temp);
ctype=cellstr(ctype);
Composite_Sequence=zeros(A,B,max(Z_Val),max(C_Val),ctype{:});


for i=1:numel(fNames)
    Image=importdata(fNames(i).name);
    if isstruct(Image)
        Composite_Sequence(:,:,Z_Val(i),C_Val(i))=Image.cdata;
    else
        Composite_Sequence(:,:,Z_Val(i),C_Val(i))=Image;
    end
end
U_Chan=unique(C_Val(C_Val~=0));
Color_Chan=cell(num_Chan,1);

for i=1:num_Chan
    Color_Chan{i,1}=Composite_Sequence(:,:,:,U_Chan(i));
end
